apiVersion: apps/v1 
kind: Deployment
metadata:
  name: menu-server
  labels:
    server: menu
spec:
  selector:
    matchLabels:
      server: menu
  replicas: 2 
  template: 
    metadata:
      labels:
        server: menu
    spec:
      containers:
      - name: menu-server
        image: docker-registry.icarcloud.net:8088/server/menuserver:1.0.0
        ports:
        - containerPort: 6000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: menu-server
  labels:
    server: menu
spec:
  selector:
    server: menu
  type: NodePort
  # clusterIP: 10.106.100.2
  ports:
  - name: http
    protocol: TCP
    nodePort: 31000
    port: 6000
    targetPort: 6000
